### ISSUE TITLE
Quest locations not spawning

### ISSUE THREAD

**Issue by Light-Wave** [chaosvolt/cdda-arcana-mod#177]
I am using Arcana (Not Arcana_BN) downloaded at 14'th of February, 2021.
After accepting the quest from the priest at the refugee center to visit the church of the cleansing flame, only 1 map tile of the building generated, instead of all 4 ground tiles and 4 roof tiles. This caused an error on completing the quest, as it was looking for surrounding map tiles to upgrade.

Generating the map tiles with the debug menu seems to be a functional workaround.

**Comment by chaosvolt** [comment]
That sounds like either an issue with DDA's mission placement code, or else somehow it didn't find any existing locations in its radius. Which is not normal, since those locations are mandatory. Might be worth testing if this happens consistently in a new world or if it's just bad RNG for that specific spot the rural church generated in.

Since the rural church spawns intact and doesn't naturally exist until created by contacting the deacon, I could use the same methods to hopefully ensure it'll reliably spawn an intact version of the location if it can't find one in its search radius.

**Comment by chaosvolt** [comment]
I noticed the one common thread there was the lack of `om_special` mentioned in the `assign_mission_target` block for those two missions. Latest commit should fix it, but do tell if you get a reoccurrence of it after updating the mod.

**Comment by Light-Wave** [comment]
I realized the two last remaining buildings were probably missing because I had added the Arcana mod after world creation, thus messing up world generation. My bad! However, the rural church was still broken when I tested in a new world.

**Comment by Light-Wave** [comment]
I can confirm that the added `on_special` fixes the issue with the church not spawning.

**Comment by chaosvolt** [comment]
Welp, definitely odd but glad that adding the special seems to help.
